// Copyright (C) 2002-2012 Nikolaus Gebhardt
// This file is part of the "Irrlicht Engine".
// For conditions of distribution and use, see copyright notice in irrlicht.h

#ifndef __BUILD_IN_FONT_H_INCLUDED__
#define __BUILD_IN_FONT_H_INCLUDED__

// header file generated by Bin2H, copyright 2002 by N.Gebhardt.
// Bin2H is Freeware. Download it freely from www.code3d.com.
// for the source bitmap, see builtInFont.bmp

#include "irrTypes.h"

namespace irr
{
namespace gui
{
	extern const u8 BuiltInFontData[];
	extern const u32 BuiltInFontDataSize;
} // end namespace gui
} // end namespace irr

#endif

