name: build

# build on c/cpp changes or workflow changes
on:
  - push
  - pull_request

jobs:
  # This is our minor gcc compiler
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install cmake g++ gcc libgl1-mesa-dev libgles2-mesa-dev libbz2-dev libpng-dev libjpeg-dev zlib1g-dev libsdl2-dev -qyy

      - name: Build
        run: |
          mkdir cmake-build-release
          cd cmake-build-release
          cmake -DCMAKE_BUILD_TYPE=Release -DIRRLICHT_VIDEO_DRIVER_OGLES1=FALSE -DIRRLICHT_VIDEO_DRIVER_OGLES2=TRUE ..
          cmake --build .

